### ISSUE TITLE
QUESTION: make load

### ISSUE THREAD

**Issue by dancesWithCycles** [fitnr/gtfs_SQL_importer#15]
Hi folks,
Thank you so much for providing and maintaining this repository. I startet to study it and keep tripping over the ```make load``` target.

I do not find in the code/scripts where and how the data from the CSV files are actually inserted into the tables. 

For instance, the column ```stops.stop_lat``` is defined as ```double precision```. How do you convert the ```string``` value from the CSV file into this db column?

For instance, the column ```stops.the_geom``` is defined as ```geometry(point, 4326),```. How do you convert the ```string``` value from the CSV file into this db column?

I found the definition of the respective trigger and function,

```
-- trigger the_geom update with lat or lon inserted
CREATE OR REPLACE FUNCTION stop_geom_update() RETURNS TRIGGER AS $stop_geom$
  BEGIN
    NEW.the_geom = ST_SetSRID(ST_MakePoint(NEW.stop_lon, NEW.stop_lat), 4326);
    RETURN NEW;
  END;
$stop_geom$ LANGUAGE plpgsql;

CREATE TRIGGER stop_geom_trigger BEFORE INSERT OR UPDATE ON stops
    FOR EACH ROW EXECUTE PROCEDURE stop_geom_update();
```

but not the actual insertion operation.

I am appreciating every hint on this issue.

Cheers!

**Comment by fitnr** [comment]
When loading from a CSV, Postgres will automatically try to coerce data into the tables data types. Assuming a well-formatted GTFS, this is no issue.

The code snippet you've pasted in is a [trigger function](https://www.postgresql.org/docs/current/plpgsql-trigger.html). As the code suggests, it runs "before insert or update on stops table". The function manipulates each row to add the `geometry` before each insert.
