### ISSUE TITLE
QUESTION: feed_index

### ISSUE THREAD

**Issue by dancesWithCycles** [fitnr/gtfs_SQL_importer#16]
Hi folks,
Thank you so much for providing and maintaining this repository. I was wondering what is the purpose of ```feed_index``` and how to we make use of it in everyday CRUD operations on the database?

Cheers!

**Comment by fitnr** [comment]
The feed index allows you to load multiple GTFS data sets into a single DB without worrying about collisions on the IDs.

Use it like any other key in a multi-column layout. There are some example queries in this repo: https://github.com/Bus-Data-NYC/nyc-bus-stats
