### ISSUE TITLE
QUESTION: shape_geoms_populate.sql AND stop_time_update_distance.sql

### ISSUE THREAD

**Issue by dancesWithCycles** [fitnr/gtfs_SQL_importer#17]
Hi folks,
Thank you so much for providing and maintaining this repository. I was wondering what is the overall purpose/topic of [this](https://github.com/fitnr/gtfs-sql-importer/blob/e42ac3fcb74cd1fdc46966a392482a414f3d4682/Makefile#L33) and [that](https://github.com/fitnr/gtfs-sql-importer/blob/e42ac3fcb74cd1fdc46966a392482a414f3d4682/Makefile#L34C77-L34C106) SQL script? Those scripts take quite some time when calling the ```load``` target. I was wondering if I can get around them to make the ```load``` target faster. 

Cheers!

**Comment by fitnr** [comment]
By default, a GTFS dataset stores geometry data in `shapes` as rows for lat/lon coordinates. The `shape_geoms` table holds the same data but stored as postgis `geometry` fields. This is easier to work with.

The `stop_time_update_distance.sql` script updates the shape_dist_traveled field if it isn't well populated.

If you don't need geometries or that field, you can safely skip these steps.
